---
name: Publish to PyPI
on:
  workflow_dispatch:
  # Trigger on published releases
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock
          pyproject-file: pyproject.toml
          python-version:
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Run tests
        # For example, using `pytest`
        run: uv run pytest
      - name: Build
        run: uv build
      - name: Publish package to PyPI
        run: uv publish
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
