---
name: Release Please
permissions:
  contents: write
  pull-requests: write
on:
  push:
    branches: [main]
    paths: [src/**, .github/workflows/**, pyproject.toml, uv.lock, README.md]
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          release-type: python
          package-name: typer-pydantic-config
          bump-minor-pre-major: true
          version-file: pyproject.toml
          changelog-path: CHANGELOG.md
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock
          pyproject-file: pyproject.toml
      - name: update lock file
        run: uv sync
      - uses: actions/checkout@v3
        with:
          ref: release-please--branches--main--components--typer-pydantic-config
      - name:
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name  "GitHub Actions"
          git add uv.lock
          git commit -m "chore: update uv.lock version"
          git push
